"""USD (Universal Scene Description) exporter.

Exports animated scene as USDA (text format) — no heavy OpenUSD dependency required.
USDA is readable by Unreal Engine, NVIDIA Omniverse, Apple Reality Composer, Pixar tools.

For binary USD (.usdc), the optional `usd-core` package can be installed.
"""

from __future__ import annotations

import logging
from pathlib import Path

import numpy as np

from app.schemas import CameraPose, Mesh3D, ObjectTrajectory4D, StructuredObject

logger = logging.getLogger(__name__)


class USDExporter:
    """Export animated scene as USDA text format."""

    def export(
        self,
        objects: list[StructuredObject],
        trajectories: dict[str, ObjectTrajectory4D],
        camera_poses: list[CameraPose] | None = None,
        output_dir: Path | None = None,
        filename: str = "scene.usda",
    ) -> Path:
        """Export as USDA file.

        Args:
            objects: Structured objects with mesh data
            trajectories: Per-object 6DoF trajectories
            camera_poses: Camera animation path
            output_dir: Output directory
            filename: Output filename (.usda for text, .usdc for binary)

        Returns:
            Path to exported USDA file
        """
        if output_dir is None:
            output_dir = Path(".")
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        output_path = output_dir / filename
        lines = []

        # ── Header ──
        lines.append('#usda 1.0')
        lines.append('(')
        lines.append('    defaultPrim = "World"')
        lines.append('    doc = "Generated by ToThinkVision 4D Scene Decomposition"')
        lines.append('    metersPerUnit = 1.0')
        lines.append('    upAxis = "Y"')

        # Time code range
        if trajectories:
            all_times = []
            for traj in trajectories.values():
                for kf in traj.keyframes:
                    all_times.append(kf.timestamp)
            if all_times:
                t_start = min(all_times)
                t_end = max(all_times)
                lines.append(f'    startTimeCode = {t_start:.4f}')
                lines.append(f'    endTimeCode = {t_end:.4f}')
                lines.append(f'    timeCodesPerSecond = 30.0')
        lines.append(')')
        lines.append('')

        # ── Materials ──
        lines.append('def Scope "Materials"')
        lines.append('{')
        for obj in objects:
            if obj.mesh_3d is None:
                continue
            mat_name = self._sanitize_name(obj.id)
            lines.append(f'    def Material "{mat_name}_mat"')
            lines.append('    {')
            lines.append(f'        def Shader "PBRShader"')
            lines.append('        {')
            lines.append('            uniform asset info:implementationSource = @usdShadeShader@')
            lines.append('            uniform token info:id = "UsdPreviewSurface"')

            # Base color from dominant color or white
            color = self._parse_color(obj.dominant_color)
            lines.append(f'            color3f inputs:diffuseColor = {color}')
            lines.append('            float inputs:metallic = 0.1')
            lines.append('            float inputs:roughness = 0.7')
            lines.append('            token outputs:surface')
            lines.append('        }')
            lines.append(f'        token outputs:surface.connect = </Materials/{mat_name}_mat/PBRShader.outputs:surface>')
            lines.append('    }')
        lines.append('}')
        lines.append('')

        # ── World root ──
        lines.append('def Xform "World"')
        lines.append('{')

        # ── Objects ──
        for obj in objects:
            if obj.mesh_3d is None:
                continue
            mesh = obj.mesh_3d
            trajectory = trajectories.get(obj.id)
            obj_name = self._sanitize_name(obj.id)

            lines.append(f'    def Xform "{obj_name}"')
            lines.append('    {')

            # Animated transform
            if trajectory and trajectory.keyframes:
                self._write_animated_transform(lines, trajectory, indent=8)
            elif obj.bbox_3d:
                x, y, z = obj.bbox_3d.x, obj.bbox_3d.y, obj.bbox_3d.z
                lines.append(f'        double3 xformOp:translate = ({x}, {y}, {z})')
                lines.append('        uniform token[] xformOpOrder = ["xformOp:translate"]')

            # Mesh
            lines.append(f'        def Mesh "{obj_name}_mesh"')
            lines.append('        {')

            # Vertices
            verts = np.array(mesh.vertices)
            vert_strs = [f"({v[0]:.6f}, {v[1]:.6f}, {v[2]:.6f})" for v in verts]
            lines.append(f'            point3f[] points = [{", ".join(vert_strs)}]')

            # Face vertex counts
            n_faces = len(mesh.faces) if mesh.faces else 0
            if n_faces > 0:
                face_counts = ", ".join(["3"] * n_faces)
                lines.append(f'            int[] faceVertexCounts = [{face_counts}]')

                # Face vertex indices
                face_indices = ", ".join(str(idx) for face in mesh.faces for idx in face)
                lines.append(f'            int[] faceVertexIndices = [{face_indices}]')

            # Normals
            if mesh.normals:
                norms = np.array(mesh.normals)
                norm_strs = [f"({n[0]:.6f}, {n[1]:.6f}, {n[2]:.6f})" for n in norms]
                lines.append(f'            normal3f[] normals = [{", ".join(norm_strs)}]')
                lines.append('            uniform token normals:interpolation = "vertex"')

            # UV coordinates
            if mesh.uv_coords:
                uv_strs = [f"({uv[0]:.6f}, {uv[1]:.6f})" for uv in mesh.uv_coords]
                lines.append(f'            texCoord2f[] primvars:st = [{", ".join(uv_strs)}]')
                lines.append('            uniform token primvars:st:interpolation = "vertex"')

            # Material binding
            lines.append(f'            rel material:material = </Materials/{obj_name}_mat>')

            lines.append('        }')  # end mesh
            lines.append('    }')  # end xform

        # ── Camera ──
        if camera_poses:
            lines.append('    def Camera "MainCamera"')
            lines.append('    {')
            lines.append('        float2 clippingRange = (0.01, 1000.0)')
            lines.append('        float focalLength = 35.0')
            lines.append('        float horizontalAperture = 36.0')
            lines.append('        float verticalAperture = 24.0')

            if len(camera_poses) > 1:
                self._write_camera_animation(lines, camera_poses, indent=8)
            elif len(camera_poses) == 1:
                p = camera_poses[0].position
                lines.append(f'        double3 xformOp:translate = ({p[0]}, {p[1]}, {p[2]})')
                lines.append('        uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ"]')

            lines.append('    }')

        # ── Ground plane (optional) ──
        lines.append('    def Mesh "GroundPlane" (')
        lines.append('        kind = "component"')
        lines.append('    )')
        lines.append('    {')
        lines.append('        point3f[] points = [(-10, 0, -10), (10, 0, -10), (10, 0, 10), (-10, 0, 10)]')
        lines.append('        int[] faceVertexCounts = [3, 3]')
        lines.append('        int[] faceVertexIndices = [0, 1, 2, 0, 2, 3]')
        lines.append('        normal3f[] normals = [(0, 1, 0), (0, 1, 0), (0, 1, 0), (0, 1, 0)]')
        lines.append('    }')

        lines.append('}')  # end World

        # ── Write file ──
        with open(output_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))

        logger.info("Exported USDA: %s", output_path)
        return output_path

    def _write_animated_transform(
        self,
        lines: list[str],
        trajectory: ObjectTrajectory4D,
        indent: int = 8,
    ):
        """Write time-sampled transform for animated object."""
        pad = " " * indent

        # Translation keyframes
        lines.append(f'{pad}double3 xformOp:translate.timeSamples = {{')
        for kf in trajectory.keyframes:
            x, y, z = kf.position
            lines.append(f'{pad}    {kf.timestamp:.4f}: ({x:.6f}, {y:.6f}, {z:.6f}),')
        lines.append(f'{pad}}}')

        # Rotation keyframes (as quaternion → euler XYZ in degrees)
        lines.append(f'{pad}double3 xformOp:rotateXYZ.timeSamples = {{')
        for kf in trajectory.keyframes:
            euler = self._quat_to_euler(kf.rotation)
            lines.append(f'{pad}    {kf.timestamp:.4f}: ({euler[0]:.4f}, {euler[1]:.4f}, {euler[2]:.4f}),')
        lines.append(f'{pad}}}')

        # Scale keyframes (if non-uniform)
        scales = np.array([kf.scale for kf in trajectory.keyframes])
        if np.any(np.abs(scales - 1.0) > 0.01):
            lines.append(f'{pad}float3 xformOp:scale.timeSamples = {{')
            for kf in trajectory.keyframes:
                sx, sy, sz = kf.scale
                lines.append(f'{pad}    {kf.timestamp:.4f}: ({sx:.4f}, {sy:.4f}, {sz:.4f}),')
            lines.append(f'{pad}}}')
            lines.append(f'{pad}uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ", "xformOp:scale"]')
        else:
            lines.append(f'{pad}uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ"]')

    def _write_camera_animation(
        self,
        lines: list[str],
        camera_poses: list[CameraPose],
        indent: int = 8,
    ):
        """Write time-sampled camera transform."""
        pad = " " * indent

        # Subsample if too many poses
        max_poses = 100
        poses = camera_poses
        if len(poses) > max_poses:
            step = len(poses) // max_poses
            poses = poses[::step]

        lines.append(f'{pad}double3 xformOp:translate.timeSamples = {{')
        for i, p in enumerate(poses):
            t = i / 30.0  # Assume 30fps
            pos = p.position if isinstance(p.position, tuple) else tuple(p.position)
            lines.append(f'{pad}    {t:.4f}: ({pos[0]}, {pos[1]}, {pos[2]}),')
        lines.append(f'{pad}}}')

        lines.append(f'{pad}double3 xformOp:rotateXYZ.timeSamples = {{')
        for i, p in enumerate(poses):
            t = i / 30.0
            rot = p.rotation if isinstance(p.rotation, tuple) else tuple(p.rotation)
            euler = self._quat_to_euler(rot)
            lines.append(f'{pad}    {t:.4f}: ({euler[0]:.4f}, {euler[1]:.4f}, {euler[2]:.4f}),')
        lines.append(f'{pad}}}')

        lines.append(f'{pad}uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ"]')

    @staticmethod
    def _quat_to_euler(q: tuple[float, float, float, float]) -> tuple[float, float, float]:
        """Convert quaternion (w, x, y, z) to Euler angles in degrees."""
        from scipy.spatial.transform import Rotation
        w, x, y, z = q
        r = Rotation.from_quat([x, y, z, w])
        return tuple(r.as_euler("xyz", degrees=True))

    @staticmethod
    def _sanitize_name(name: str) -> str:
        """Make a valid USD identifier."""
        return "".join(c if c.isalnum() or c == "_" else "_" for c in name).strip("_") or "object"

    @staticmethod
    def _parse_color(color_str: str | None) -> str:
        """Parse hex color to USD color3f format."""
        if color_str and color_str.startswith("#") and len(color_str) == 7:
            try:
                r = int(color_str[1:3], 16) / 255.0
                g = int(color_str[3:5], 16) / 255.0
                b = int(color_str[5:7], 16) / 255.0
                return f"({r:.3f}, {g:.3f}, {b:.3f})"
            except ValueError:
                pass
        return "(0.8, 0.8, 0.8)"
